# Generated by Django 4.1.3 on 2022-12-01 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
