# Generated by Django 4.1.3 on 2022-12-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_delete_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='middlename',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
